Name:           ros-kinetic-gennodejs
Version:        2.0.1
Release:        0%{?dist}
Summary:        ROS gennodejs package
Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/gennodejs
Source0:        %{name}-%{version}.tar.gz
Source1001:     %{name}.manifest
BuildRequires:  gcc-c++
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-genmsg
Requires:       ros-kinetic-genmsg

%description
Standalone Python library for generating ROS message and service data structures
for various languages.

%prep
%setup -q
cp %{SOURCE1001} .

%build
%{__ros_setup}
%{__ros_build}

%install
%{__ros_setup}
%{__ros_install}

%files -f build/install_manifest.txt
%manifest %{name}.manifest
%defattr(-,root,root)
%{__ros_install_path}/lib/python2.7/site-packages/*

%changelog
* Fri Apr 08 2017 Zhang Xingtao <xingtao.zhang@yahoo.com> - 2.0.1
* Fri May 09 2014 Dirk Thomas <dthomas@osrfoundation.org> - 0.4.23-0
- Autogenerated by Bloom
